/* Generated By:JavaCC: Do not edit this line. Parser0Constants.java */
package ICLCompiler;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parser0Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 5;
  /** RegularExpression Id. */
  int DEF = 6;
  /** RegularExpression Id. */
  int IN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int DEREF = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int PRINTLN = 20;
  /** RegularExpression Id. */
  int EQUALS = 21;
  /** RegularExpression Id. */
  int HIGHEREQ = 22;
  /** RegularExpression Id. */
  int HIGHER = 23;
  /** RegularExpression Id. */
  int SMALLEREQ = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int NEG = 27;
  /** RegularExpression Id. */
  int SMALLER = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int EQUAL = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;
  /** RegularExpression Id. */
  int DOUBSEMICOLON = 34;
  /** RegularExpression Id. */
  int MUL = 35;
  /** RegularExpression Id. */
  int MOD = 36;
  /** RegularExpression Id. */
  int DIV = 37;
  /** RegularExpression Id. */
  int LPAR = 38;
  /** RegularExpression Id. */
  int RPAR = 39;
  /** RegularExpression Id. */
  int ID = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<Num>",
    "\"def\"",
    "\"in\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\":=\"",
    "\"!\"",
    "\"new\"",
    "\"print\"",
    "\"println\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\"<\"",
    "\"not\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\";\"",
    "\";;\"",
    "\"*\"",
    "\"%\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<ID>",
  };

}
